# Generated by Django 5.2.7 on 2025-10-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resumes', '0002_job_embedding_resume_embedding_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='resumes_job_embeddi_c9f71b_gin',
        ),
        migrations.RemoveField(
            model_name='job',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='resumes_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='resumes_user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
